import { randomBytes } from "node:crypto";
import { chmod, writeFile } from "node:fs/promises";
import path from "node:path";

function secret(): string {
  return randomBytes(32).toString("base64url");
}

export async function setupRemoteGateway(outputPath = path.resolve(process.cwd(), ".browsercontrol.env")) {
  const deviceToken = secret();
  const mcpToken = secret();
  const adminToken = secret();
  const contents = [
    "# Generated by browserControl. Keep this file private.",
    "BROWSERCONTROL_GATEWAY_HOST=127.0.0.1",
    "BROWSERCONTROL_GATEWAY_PORT=8787",
    `BROWSERCONTROL_DEVICE_TOKEN=${deviceToken}`,
    `BROWSERCONTROL_MCP_TOKEN=${mcpToken}`,
    `BROWSERCONTROL_ADMIN_TOKEN=${adminToken}`,
    "",
  ].join("\n");

  await writeFile(outputPath, contents, { encoding: "utf8", mode: 0o600 });
  try {
    await chmod(outputPath, 0o600);
  } catch {
    // Windows and some filesystems do not implement POSIX mode bits.
  }

  console.log("browserControl gateway credentials created.");
  console.log(`Environment file: ${outputPath}`);
  console.log("");
  console.log("Chrome extension configuration:");
  console.log("  Gateway WebSocket (local development only): ws://127.0.0.1:8787/extension");
  console.log("  Deployed gateway WebSocket:               wss://YOUR_GATEWAY_HOST/extension");
  console.log(`  Local development device token: ${deviceToken}`);
  console.log("  Deployed gateways should pair revocable devices instead of using BROWSERCONTROL_DEVICE_TOKEN.");
  console.log("");
  console.log("Local MCP endpoint:");
  console.log(`  http://127.0.0.1:8787/mcp?token=${encodeURIComponent(mcpToken)}`);
  console.log("  Use HTTPS/WSS and the Authorization header for a deployed gateway.");
  console.log("");
  console.log("Admin API bearer token:");
  console.log(`  ${adminToken}`);
  console.log("  This token is only for pairing/device administration; never give it to an AI connector.");
  console.log("");
  console.log("Start the gateway with:");
  if (process.platform === "win32") {
    console.log("  Load .browsercontrol.env into your environment, then run: npm run gateway");
  } else {
    console.log("  set -a; source .browsercontrol.env; set +a; npm run gateway");
  }

  return { outputPath, deviceToken, mcpToken, adminToken };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  setupRemoteGateway().catch((error) => {
    console.error("Failed to initialize browserControl gateway:", error);
    process.exit(1);
  });
}
