import { randomBytes } from "node:crypto";
import { chmod, writeFile } from "node:fs/promises";
import path from "node:path";

function secret(): string {
  return randomBytes(32).toString("base64url");
}

export async function setupRemoteGateway(outputPath = path.resolve(process.cwd(), ".browsercontrol.env")) {
  const deviceToken = secret();
  const mcpToken = secret();
  const adminToken = secret();
  const contents = [
    "# Generated by browserControl for LOOPBACK DEVELOPMENT. Keep this file private.",
    "BROWSERCONTROL_GATEWAY_HOST=127.0.0.1",
    "BROWSERCONTROL_GATEWAY_PORT=8787",
    `BROWSERCONTROL_DEVICE_TOKEN=${deviceToken}`,
    `BROWSERCONTROL_MCP_TOKEN=${mcpToken}`,
    `BROWSERCONTROL_ADMIN_TOKEN=${adminToken}`,
    "",
  ].join("\n");

  await writeFile(outputPath, contents, { encoding: "utf8", mode: 0o600 });
  try {
    await chmod(outputPath, 0o600);
  } catch {
    // Windows and some filesystems do not implement POSIX mode bits.
  }

  console.log("browserControl loopback-development credentials created.");
  console.log(`Environment file: ${outputPath}`);
  console.log("");
  console.log("Local Chrome extension configuration:");
  console.log("  Relay WebSocket: ws://127.0.0.1:8787/extension");
  console.log(`  Local development device token: ${deviceToken}`);
  console.log("");
  console.log("Local MCP endpoint:");
  console.log("  http://127.0.0.1:8787/mcp");
  console.log(`  Use header: Authorization: Bearer ${mcpToken}`);
  console.log("");
  console.log("Admin API bearer token:");
  console.log(`  ${adminToken}`);
  console.log("");
  console.log("For a PUBLIC relay, do not deploy the generated BROWSERCONTROL_DEVICE_TOKEN or BROWSERCONTROL_MCP_TOKEN.");
  console.log("Deploy only BROWSERCONTROL_ADMIN_TOKEN, create an 8-digit pairing code, and pair the extension.");
  console.log("Pairing issues a unique extension token plus a unique MCP connector token for that device.");
  console.log("The extension then shows the device-scoped HTTPS /mcp connector URL to add to Claude.");
  console.log("");
  console.log("Start this local gateway with:");
  if (process.platform === "win32") {
    console.log("  Load .browsercontrol.env into your environment, then run: npm run gateway");
  } else {
    console.log("  set -a; source .browsercontrol.env; set +a; npm run gateway");
  }

  return { outputPath, deviceToken, mcpToken, adminToken };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  setupRemoteGateway().catch((error) => {
    console.error("Failed to initialize browserControl gateway:", error);
    process.exit(1);
  });
}
